services:
  db:
    image: mysql:latest
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
    - .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"

  app:
    build:
      dockerfile: ./Dockerfile
    command: >
      sh -c "/wait-for-it.sh db:3306 -- python manage.py migrate &&
      gunicorn test_task.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - static_data:/app/staticfiles
      - static_data:/app/media
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_data:/usr/share/nginx/html/test_task/static
      - static_data:/usr/share/nginx/html/test_task/media
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  mysql_data:
  static_data: